### ISSUE TITLE
按照WIKI中文详细编译手册安装失败

### ISSUE THREAD

**Issue by BenDerPan** [tencent-wechat/phxrpc#11]
按照中文详细编译手册安装，发现文档已经过时了，protobuf在googlecode的地址已经失效了，而且github上的protobuf现在不带gtest了，需要自己安装了，自动安装脚本需要同步更新下

**Comment by Wizmann** [comment]
可以直接放编译好的二进制进去

**Comment by BenDerPan** [comment]
刚直接下载protobuf3.0.2的Release版本（包含所有需要的）安装了，可以了，感谢~~。
