### ISSUE TITLE
UThreadRuntime 改进建议

### ISSUE THREAD

**Issue by hzhxxx** [tencent-wechat/phxrpc#12]
1. UThreadRuntime类中的 void UThreadRuntime :: UThreadDoneCallback() 是否考虑对执行完成
的 ContextSlot 剔除出 context_list_ 数组,这样可以加快没有完成的 UThreadContext 被选中的几率，
比如通过例子 test_uthread(test_uthread.cpp)来执行，在
 for(; ! runtime.IsAllDone(); ) {
        int seq = random() % count;
        runtime.Resume( args[ seq ].id );
    }
这段代码中,最后一个没有执行完成的UThreadContext 可能要随机被选中，需要空转很多次才能选中。
2. UThreadRuntime::IsAllDone(),这个函数建议直接返回 unfinished_item_count_即可,这样就能立即
获取到队列中没有执行完成总数。
3. 执行完成的任务立即剔除出执行数组，那创建函数
int UThreadRuntime :: Create(UThreadFunc_t func, void * args) 也可以简化很多,不用去抢占执行完成的坑了

**Comment by lynncui00** [comment]
您好。
1. 一般`UThreadRuntime`类的使用方式都建议由外部进行`Context`的管理，可参考`UThreadEpoll`。在这种管理模式下没有您说的问题，关于测试代码确实比较简陋。
3. 数组的剔除操作是一个非常重的操作，所以完成队列这样的优化机制。
