### ISSUE TITLE
采用汇编实现协程上下文保存

### ISSUE THREAD

**Issue by berockguo** [tencent-wechat/phxrpc#2]
ucontext做了很多不必要的事情，只需要保存6个寄存器以及栈即可实现协程切换的需求。

**Comment by lynncui00** [comment]
这个问题我们有考虑过，但针对实际测试情况，我们认为这里不是主要瓶颈，而boost的context库性能已经足够，所以暂时不会做这件事，后续如果出现瓶颈变化我们可能会考虑。也因为这个问题，我们编写了boost context for phxrpc的插件，只需要准备好boost库并改一行Makefile代码即可开启boost优化。
