### ISSUE TITLE
MakeFile怎么转Makefile.define

### ISSUE THREAD

**Issue by liaobinxu** [tencent-wechat/phxrpc#20]
phxrpc 中Makefile 怎么转 phxsql中Makefile.define
`
phxbinlogsvr/framework/proto/phxbinlogsvr.proto
phxbinlogsvr/framework/proto/Makefile.define
phxbinlogsvr/framework/rpccomm/Makefile.define
phxbinlogsvr/framework/phxrpc/client/Makefile.define
phxbinlogsvr/framework/phxrpc/svr/Makefile.define
phxbinlogsvr/framework/phxrpc/tools/Makefile.define`

**Comment by lynncui00** [comment]
这个是phxsql的代码，按phxsql的编译步骤进行就可以转出来了。
