### ISSUE TITLE
配置Config类section的处理

### ISSUE THREAD

**Issue by liubotao** [tencent-wechat/phxrpc#23]
> 
    char tmp_section[128] = { 0 };
    snprintf(tmp_section, sizeof(tmp_section), "\n[%s]", section);

    char tmp_key[128] = { 0 };
    snprintf(tmp_key, sizeof(tmp_key), "\n%s", key);

如上配置类中关于,tmp_section的初始化格式，测试用于读取下面配置信息。

> 
    [Server]
    BindIP = 127.0.0.1          //Server IP
    Port = 16161                //Server Port
    MaxThreads = 16             //Worker 线程数
    IOThreadCount = 3           //IO线程数，针对业务请自行调节
    PackageName = search        //Server 名字，用于自行实现的监控统计上报
    MaxConnections = 800000     //最大并发连接数
    MaxQueueLength = 20480      //IO队列最大长度
    FastRejectThresholdMS = 20  //快速拒绝自适应调节阀值，建议保持默认20ms，不做修改

    [ServerTimeout]
    SocketTimeoutMS = 5000      //Server读写超时，Worker处理超时

因为tmp_section初始化为\n[%s]格式，如果[Server]section配置选没有\n在二行而是在首行则无法匹配，从而导致无法获取Server区块的配置信息。

**Comment by liusifan** [comment]
是存在这个问题。在最近的一次提交中已经fix这个问题，请从git上面更新一下最新的代码。
