### ISSUE TITLE
快速拒绝速率可配置

### ISSUE THREAD

**Issue by berockguo** [tencent-wechat/phxrpc#3]
通过率的增长速度和下载速度可配置。

**Comment by lynncui00** [comment]
谢谢你的建议，我们会考虑增加这个配置。目前快速拒绝的所有参数都是在微信后台多年的海量实践里面验证过的比较优秀的经验值。

**Comment by lynncui00** [comment]
您好，通过率的调整速度已经可以配置。

**Comment by berockguo** [comment]
多谢lynn。另外，能否耦合类似zk，提供服务治理的能力呢。
