### ISSUE TITLE
编译错误，protobuf用的是3.0，请教下是什么问题呢

### ISSUE THREAD

**Issue by luooo** [tencent-wechat/phxrpc#5]
![image](https://cloud.githubusercontent.com/assets/10449936/18033177/9cc2c730-6d4e-11e6-9182-55e8eaf2496f.png)

**Comment by berockguo** [comment]
请确认你的protoc是3.0版本的

**Comment by shijianlau** [comment]
我编译也碰到一个问题，请教了：
make[1]: Leaving directory `/root/software/phxrpc/codegen'
./regen.sh: line 5: 10800 段错误               ../codegen/phxrpc_pb2server -I ../ -I ../third_party/protobuf/include -f search.proto -d .
make[1]: Entering directory `/root/software/phxrpc/sample'
make[1]: *** 没有指明目标并且找不到 makefile。 停止。
make[1]: Leaving directory `/root/software/phxrpc/sample'
make: *** [all] 错误 2

**Comment by lynncui00** [comment]
在sample目录运行命令../codegen/phxrpc_pb2server -I ../ -I ../third_party/protobuf/include -f search.proto -d .试试，看起来是segmentfault了，你的操作系统环境是啥？

**Comment by shijianlau** [comment]
@lynncui00 我的系统是Centos 6.5 x86_64，后面升级了gcc，最后到了对phxsql执行make时再次出错了：
phxsql/third_party/glog/lib/libglog.a(utilities.cc.o)：在函数‘google::GetStackTrace(void**, int, int)’中：
utilities.cc:(.text+0x73e)：对‘_Ux86_64_getcontext’未定义的引用
utilities.cc:(.text+0x757)：对‘_ULx86_64_init_local’未定义的引用
utilities.cc:(.text+0x7af)：对‘_ULx86_64_get_reg’未定义的引用
utilities.cc:(.text+0x7f4)：对‘_ULx86_64_step’未定义的引用
collect2: error: ld returned 1 exit status
make[4]: *** [phxbinlogsvr_phxrpc] 错误 1
make[4]: Leaving directory `phxsql/phxbinlogsvr/framework/phxrpc/svr'
make[3]: *** [sub_dir] 错误 1
make[3]: Leaving directory `phxsql/phxbinlogsvr/framework/phxrpc'
make[2]: *** [sub_dir] 错误 1
make[2]: Leaving directory `phxsql/phxbinlogsvr/framework'
make[1]: *** [sub_dir] 错误 1
make[1]: Leaving directory `phxsql/phxbinlogsvr'
make: *** [sub_dir] 错误 1

**Comment by lynncui00** [comment]
@shijianlau 您好，请问phxrpc的问题解决了么，如果有phxrpc的问题请继续在这里反馈，有关phxsql的问题到phxsql的issues提出较好，这样大家解决的过程思路也能让大家看到。谢谢。
